CoursesView: Bug: the _userId was set even if the request returned was not valid, this of course leads to NoSuchMethodError's So I just moved the userId after the course.isEmpty check